context.modules = [
{   name = libpipewire-module-pal
    args = {
        node.name = "pal_sink_speaker"
        node.description = "pal sink speaker"
        stream.props = {
            audio.position = [ FL FR ]
        }
        media.class = "Audio/Sink"
        media.role = "music"
    }
},
{   name = libpipewire-module-pal
    args = {
        node.name = "pal_sink_headset"
        node.description = "pal sink headset"
        stream.props = {
            audio.position = [ FL FR ]
        }
        media.class = "Audio/Sink"
        media.role = "music"
    }
},
{   name = libpipewire-module-pal
    args = {
        node.name = "pal_source_speaker_mic"
        node.description = "pal source handset mic"
        stream.props = {
            audio.position = [ FL FR ]
        }
        media.class = "Audio/Source"
    }
},
{   name = libpipewire-module-pal
    args = {
        node.name = "pal_source_headset_mic"
        node.description = "pal source headset mic"
        stream.props = {
            audio.position = [ FL FR ]
        }
        media.class = "Audio/Source"
    }
},
{   name = libpipewire-module-pal
    args = {
        node.name = "pal_sink_dp_out"
        node.description = "pal sink dp audio"
        stream.props = {
            audio.position = [ FL FR ]
        }
        media.class = "Audio/Sink"
        media.role = "notification"
        jack-name = "HDMI/DP0 Jack"
    }
},
{   name = libpipewire-module-pal
    args = {
        node.name = "pal_sink_hdmi_out"
        node.description = "pal sink hdmi audio"
        stream.props = {
            audio.position = [ FL FR ]
        }
        media.class = "Audio/Sink"
        media.role = "notification"
        jack-name = "HDMI/DP1 Jack"
    }
}
]
