GP0{
    # 支持项目列表(support projects)
    project_list:[
        "QSM565DWF"
    ]
    custoct_list:[
        # 两个维度(two dimensions): OS + VERSION
        "LINUX"
        "STD"
        "DBG"
        "SEC"
        "UBUNTU"
        "DEBIAN"
    ]
    flash {}
    macro {}
    function {}
    # 文件操作(file operate)
    common {
        git {
            #"git":["a", "b"],
        }
        copy {
            # src file patch  : dst file patch(如果有多个目标目录，可以使用列表形式 [A, B,C...])
        }
        symlink {}
        delete:[]
    }
    custom {
        LINUX {
            git {}
            copy {}
            symlink {
            }
            delete:[
            ]
        }
        STD {
            git {}
            copy {}
            symlink {
            }
            delete:[
            ]
        }
        DBG {
            git {}
            copy {}
            symlink {
            }
            delete:[
            ]
        }
        SEC {
            macro {
                SECBOOT_ENABLE:"1"
            }
            git {}
            copy {}
            symlink {
            }
            delete:[
            ]
        }
        UBUNTU {
            git {}
            copy {}
            symlink {
            }
            delete:[
            ]
        }
        DEBIAN {
            git {}
            copy {}
            symlink {
            }
            delete:[
            ]
        }
    }
}
